[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server-less"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200